services:
  web:
    image: ghcr.io/dm-nosov/boostress/boostress:latest
    hostname: web
    environment:
      - DJANGO_DEBUG=False
      - TRUSTED_ORIGINS=http://localhost
      - VIRTUAL_HOST=localhost
      - ALLOWED_HOSTS=localhost
      - POSTGRES_DB=boostress
      - POSTGRES_USER=boostress
      - ADMIN_USER=admin
      - ADMIN_EMAIL=email@example.com
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password     
    ports:
      - "8000:8000"      
    secrets:
      - django_secret_key
      - postgres_password
      - admin_password
      - redis_password
    depends_on:
      - db
      - message_broker
    volumes:
      - ./logs/django:/app/logs/django
      - static_files:/app/static
      - conf_files:/app/conf

  db:
    image: postgres:15-alpine
    hostname: db
    environment:
      - POSTGRES_DB=boostress
      - POSTGRES_USER=boostress
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    secrets:
      - postgres_password

  message_broker:
    image: redis:latest
    hostname: message_broker
    ports:
      - "6379:6379"
    command: ["sh", "-c", "redis-server --requirepass $$(cat /run/secrets/redis_password)"]
    secrets:
      - redis_password

  scheduler:
    image: ghcr.io/dm-nosov/boostress/boostress:latest
    command: ["/app/conf/celery/scheduler_launch.sh"]
    environment:
      - DJANGO_DEBUG=False
      - POSTGRES_DB=boostress
      - POSTGRES_USER=boostress
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password 
    secrets:
      - postgres_password
      - redis_password
    volumes:
      - ./logs/celery:/app/logs/celery
    depends_on:
      - message_broker
      - db


  worker:
    image: ghcr.io/dm-nosov/boostress/boostress:latest
    command: ["/app/conf/celery/worker_launch.sh"]
    environment:
      - DJANGO_DEBUG=False
      - POSTGRES_DB=boostress
      - POSTGRES_USER=boostress
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password       
    secrets:
      - postgres_password
      - redis_password
    volumes:
      - ./logs/celery:/app/logs/celery
    depends_on:
      - message_broker
      - db
    healthcheck:
      test: ["CMD", "celery", "-A", "boostress", "inspect", "ping"]

  nginx:
    image: nginx:alpine
    hostname: nginx
    ports:
      - "127.0.0.1:1080:80"
    volumes:
      - static_files:/var/www/static
      - conf_files:/app/conf
    entrypoint: ["/app/conf/nginx/add_env_vars.sh", "nginx", "-g", "daemon off;"]
    depends_on:
      - web

secrets:
  django_secret_key:
    external: true
  postgres_password:
    external: true
  admin_password:
    external: true
  redis_password:
    external: true

volumes:
  static_files:
  conf_files:
