# Generated by Django 5.1.1 on 2024-11-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign_manager', '0027_platformservice_end_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.CharField(default='', max_length=255)),
                ('endpoint_url', models.CharField(default='', max_length=255)),
                ('token', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AgentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('label', models.CharField(default='', max_length=50)),
                ('message_qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AgentOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Processing', 'processing'), ('In progress', 'in_progress'), ('Completed', 'completed'), ('Partial', 'in_progress'), ('Canceled', 'completed'), ('Pre_complete', 'pre_complete')], default='Pending', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_cloud.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'pending'), ('Processing', 'processing'), ('In progress', 'in_progress'), ('Completed', 'completed'), ('Partial', 'in_progress'), ('Canceled', 'completed'), ('Pre_complete', 'pre_complete')], default='Pending', max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_cloud.agent')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_manager.platformservice')),
            ],
        ),
        migrations.CreateModel(
            name='AgentOpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ref_id', models.CharField(default='', max_length=50)),
                ('ref_url', models.CharField(default='', max_length=255)),
                ('is_fwd', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_cloud.endpoint')),
            ],
        ),
    ]
