# Generated by Django 5.1.1 on 2024-11-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentservice',
            name='is_ref',
            field=models.BooleanField(default=False),
        ),
    ]
