# Generated by Django 5.1.1 on 2025-07-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_cloud', '0002_agentservice_is_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresource',
            name='resource_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='json_params',
            field=models.JSONField(default=dict),
        ),
    ]
