# Generated by Django 5.1.1 on 2025-08-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_cloud', '0003_agentresource_resource_type_endpoint_json_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresource',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
