# Generated by Django 5.1.1 on 2024-09-08 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetask',
            name='budget',
        ),
        migrations.AddField(
            model_name='servicetask',
            name='link',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='link_type',
            field=models.CharField(choices=[('profile', 'profile'), ('post', 'post')], default='post', max_length=20),
        ),
        migrations.AddField(
            model_name='servicetask',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_manager.provider'),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='spent',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('completed', 'completed')], default='pending', max_length=20)),
                ('link', models.CharField(default='', max_length=256)),
                ('link_type', models.CharField(choices=[('profile', 'profile'), ('post', 'post')], default='post', max_length=20)),
                ('spent', models.FloatField(default=0.0)),
                ('budget', models.FloatField(default=5)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign_manager.providerplatform')),
            ],
        ),
    ]
