# Generated by Django 5.1.1 on 2024-09-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0007_alter_servicetask_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
