# Generated by Django 5.1.1 on 2024-09-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0009_rename_platform_providerplatform_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='campaign_manager.provider'),
        ),
    ]
