# Generated by Django 5.1.1 on 2024-09-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0010_alter_platformservice_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformservice',
            name='link_type',
            field=models.CharField(choices=[('profile', 'profile'), ('post', 'post')], default='post', max_length=20),
        ),
    ]
