# Generated by Django 5.1.1 on 2024-09-09 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0011_platformservice_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='ext_order_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaign_manager.provider'),
        ),
    ]
