# Generated by Django 5.1.1 on 2024-09-09 16:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0012_servicetask_ext_order_id_alter_servicetask_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetask',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetask',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In progress', 'in_progress'), ('Completed', 'completed'), ('Partial', 'in_progress'), ('Canceled', 'completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In progress', 'in_progress'), ('Completed', 'completed'), ('Partial', 'in_progress'), ('Canceled', 'completed')], default='Pending', max_length=20),
        ),
    ]
