# Generated by Django 5.1.1 on 2024-09-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0014_servicetask_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.IntegerField(default=2880),
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='platformservice',
            name='pre_complete_minutes',
            field=models.IntegerField(default=2880, help_text='Duration in minutes before running the next task of the same type. Default is 48 hours.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Processing', 'processing'), ('In progress', 'in_progress'), ('Completed', 'completed'), ('Partial', 'in_progress'), ('Canceled', 'completed'), ('Pre_complete', 'pre_complete')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='providerplatform',
            name='name',
            field=models.CharField(choices=[('ln', 'linkedin'), ('tt', 'tiktok'), ('tg', 'telegram'), ('ig', 'instagram')], default='ln', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicetask',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Processing', 'processing'), ('In progress', 'in_progress'), ('Completed', 'completed'), ('Partial', 'in_progress'), ('Canceled', 'completed'), ('Pre_complete', 'pre_complete')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('share', 'share'), ('view', 'view'), ('repost', 'repost'), ('send', 'send'), ('follow', 'follow')], default='view', max_length=20),
        ),
    ]
