# Generated by Django 5.1.1 on 2024-09-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0015_order_deadline_order_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='campaign_manager.order'),
        ),
    ]
