# Generated by Django 5.1.1 on 2024-09-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0016_alter_servicetask_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetask',
            name='pre_complete_minutes',
            field=models.IntegerField(default=2880, help_text='Duration in minutes before running the next task of the same type. Default is 48 hours.'),
        ),
    ]
