# Generated by Django 5.1.1 on 2024-09-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0017_servicetask_pre_complete_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_followers',
            field=models.IntegerField(default=50),
        ),
    ]
