# Generated by Django 5.1.1 on 2024-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0018_order_total_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_sensible',
            field=models.BooleanField(default=False, help_text='The QTYs mimic the decrease in the attention span throughout the time'),
        ),
    ]
