# Generated by Django 5.1.1 on 2024-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0022_platformservice_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('link_type', models.CharField(choices=[('profile', 'profile'), ('post', 'post'), ('comment', 'comment'), ('ads_post', 'ads_post'), ('web_traffic', 'web_traffic')], default='post', max_length=20, null=True)),
                ('service_type', models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('share', 'share'), ('view', 'view'), ('repost', 'repost'), ('send', 'send'), ('follow', 'follow'), ('com_emoji', 'com_emoji'), ('visit', 'visit')], default='view', max_length=20, null=True)),
                ('platform_name', models.CharField(choices=[('ln', 'linkedin'), ('tt', 'tiktok'), ('tg', 'telegram'), ('ig', 'instagram')], default='ln', max_length=20, null=True)),
                ('min', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='platformservice',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_sensible',
            field=models.BooleanField(default=True, help_text='The QTYs mimic the decrease in the attention span throughout the time'),
        ),
    ]
