# Generated by Django 5.1.1 on 2024-10-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0023_engagementconfig_platformservice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='natural_time_cycles',
            field=models.BooleanField(default=False, help_text='Use with something permanently running to mimic the changes to datetime activity cycles'),
        ),
        migrations.AlterField(
            model_name='engagementconfig',
            name='link_type',
            field=models.CharField(blank=True, choices=[('profile', 'profile'), ('post', 'post'), ('comment', 'comment'), ('ads_post', 'ads_post'), ('web_traffic', 'web_traffic')], default='post', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='engagementconfig',
            name='platform_name',
            field=models.CharField(blank=True, choices=[('ln', 'linkedin'), ('tt', 'tiktok'), ('tg', 'telegram'), ('ig', 'instagram')], default='ln', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='engagementconfig',
            name='service_type',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('comment', 'comment'), ('share', 'share'), ('view', 'view'), ('repost', 'repost'), ('send', 'send'), ('save', 'save'), ('follow', 'follow'), ('com_emoji', 'com_emoji'), ('visit', 'visit'), ('video_view', 'video_view')], default='view', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('share', 'share'), ('view', 'view'), ('repost', 'repost'), ('send', 'send'), ('save', 'save'), ('follow', 'follow'), ('com_emoji', 'com_emoji'), ('visit', 'visit'), ('video_view', 'video_view')], default='view', max_length=20),
        ),
    ]
