# Generated by Django 5.1.1 on 2024-10-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0024_order_natural_time_cycles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='api_type',
            field=models.CharField(choices=[('b11d', 'b11d'), ('u1u', 'u1u')], default='b11d', max_length=20),
        ),
    ]
