# Generated by Django 5.1.1 on 2024-10-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0025_provider_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformservice',
            name='service_meta',
            field=models.TextField(default=''),
        ),
    ]
