# Generated by Django 5.1.1 on 2024-10-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0026_platformservice_service_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformservice',
            name='end_after',
            field=models.IntegerField(default=99999),
        ),
        migrations.AddField(
            model_name='platformservice',
            name='start_after',
            field=models.IntegerField(default=0),
        ),
    ]
