# Generated by Django 5.1.1 on 2025-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_manager', '0028_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extras',
            field=models.TextField(default='{}'),
        ),
    ]
