name: Build and Push Boostress image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        # Build the image
        docker build -t ghcr.io/${{ github.repository }}/boostress:${{ github.event.release.tag_name }} .

        # Tag the image with multiple tags
        docker tag ghcr.io/${{ github.repository }}/boostress:${{ github.event.release.tag_name }} ghcr.io/${{ github.repository }}/boostress:latest
        docker tag ghcr.io/${{ github.repository }}/boostress:${{ github.event.release.tag_name }} ghcr.io/${{ github.repository }}/boostress:${{ github.sha }}

        # Push the images with all tags
        docker push ghcr.io/${{ github.repository }}/boostress:${{ github.event.release.tag_name }}
        docker push ghcr.io/${{ github.repository }}/boostress:latest
        docker push ghcr.io/${{ github.repository }}/boostress:${{ github.sha }}
